[package]
name = "galloc-basic-example"
version = "0.1.0"
authors = ["Zakarum <zakarumych@ya.ru>"]
edition = "2018"
publish = false

[dependencies]
galloc = { path = "../../galloc", version = "=0.1" }
galloc-mock = { path = "../../mock", version = "=0.1" }
eyre = "0.6"
color-eyre = "0.5"
